{
 "title": "CAMARA Data Pipeline Live Dashboard",
 "tags": [
  "camara",
  "pipeline"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pipeline System Throughput (rec/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(fastapi_requests_total[1m]) or rate(spark_processed_rows_total[1m])",
     "legendFormat": "{{job}} Throughput"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag per Topic/Partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=~\"radius.*\"}",
     "legendFormat": "{{topic}} - Partition {{partition}}"
    }
   ]
  },
  {
   "title": "API Latency Percentile 95 (p95) Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, path, job))",
     "legendFormat": "{{job}} [{{path}}] p95"
    }
   ]
  }
 ]
}