port 26379
dir /tmp
sentinel monitor camara-master camara-redis 6379 2
sentinel down-after-milliseconds camara-master 5000
sentinel failover-timeout camara-master 60000
sentinel parallel-syncs camara-master 1
